// usage: log('inside coolFunc', this, arguments);
// paulirish.com/2009/log-a-lightweight-wrapper-for-consolelog/
window.log = function f(){ log.history = log.history || []; log.history.push(arguments); if(this.console) { var args = arguments, newarr; args.callee = args.callee.caller; newarr = [].slice.call(args); if (typeof console.log === 'object') log.apply.call(console.log, console, newarr); else console.log.apply(console, newarr);}};

// make it safe to use console.log always
(function(a){function b(){}for(var c="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),d;!!(d=c.pop());){a[d]=a[d]||b;}})
(function(){try{console.log();return window.console;}catch(a){return (window.console={});}}());


// place any jQuery/helper plugins in here, instead of separate, slower script files.

/* Rainbow v1.0 rainbowco.de | included languages: generic */
window.Rainbow=function(){function q(a){var d=a.getAttribute&&a.getAttribute("data-language")||null;if(!d){var a=a.attributes.length,c;for(c=0;c<a;++c)"data-language"==="data-language"[c].nodeName&&(d="data-language"[c].nodeValue)}return d}function C(a,d){for(var c in g[f]){c=parseInt(c,10);if(a==c&&d==g[f][c]?0:a<=c&&d>=g[f][c])delete g[f][c],delete i[f][c];if(a>=c&&a<g[f][c]||d>c&&d<g[f][c])return!0}return!1}function r(a,d){return'<span class="'+a.replace(/\./g," ")+(l?" "+l:"")+'">'+d+"</span>"}
function D(a,d){var c=0,e;for(e=1;e<d;++e)a[e]&&(c+=a[e].length);return c}function s(a,d,c,e){var k=a.exec(c);if(k){++t;!d.name&&d.matches[0]&&(d.name=d.matches[0],delete d.matches[0]);var h=k[0],j=k.index,u=k[0].length+j,m=function(){function k(){s(a,d,c,e)}t%100>0?k():setTimeout(k,0)};if(C(j,u))m();else{var n=v(d.matches),l=function(c,a,e){if(c>=a.length)e(h);else{var f=function(){l(++c,a,e)},g=k[a[c]];if(g){var j=d.matches[a[c]],i=j.language;if(i)w(g,i,function(c){h=h.replace(g,c);f()});else if(typeof j===
"object")x(g,j.length?j:[j],function(c){h=h.replace(g,c);f()});else{h=y(D(k,a[c]),g,r(j,g),h);f()}}else f()}};l(0,n,function(c){d.name&&(c=r(d.name,c));if(!i[f]){i[f]={};g[f]={}}i[f][j]={replace:k[0],"with":c};g[f][j]=u;m()})}}else e()}function E(a){var d=n[a]||[],c=n[z]||[];return A[a]?d:d.concat(c)}function y(a,d,c,e){return e.substr(0,a)+e.substr(a).replace(d,c)}function v(a){var d=[],c;for(c in a)a.hasOwnProperty(c)&&d.push(c);return d.sort(function(c,a){return a-c})}function x(a,d,c){function e(d,
h){h<d.length?s(d[h].pattern,d[h],a,function(){e(d,++h)}):F(a,function(a){delete i[f];delete g[f];--f;c(a)})}++f;e(d,0)}function F(a,d){function c(a,d,e,g){if(e<d.length){++B;var m=d[e],l=i[f][m],a=y(m,l.replace,l["with"],a),m=function(){c(a,d,++e,g)};0<B%250?m():setTimeout(m,0)}else g(a)}var e=v(i[f]);c(a,e,0,d)}function w(a,d,c){x(a,E(d),function(a){c(a)})}function o(a,d){if(d<a.length){var c=q(a[d])||q(a[d].parentNode);c?(c=c.toLowerCase(),a[d].className=c,w(a[d].innerHTML,c,function(e){a[d].innerHTML=
e;i={};g={};p&&p(a[d],c);setTimeout(function(){o(a,++d)},0)})):o(a,++d)}}var i={},g={},n={},A={},f=0,z=0,t=0,B=0,l,p;return{extend:function(a,d,c){1==arguments.length&&(d=a,a=z);A[a]=c;n[a]=d.concat(n[a]||[])},d:function(a){p=a},c:function(a){l=a},a:function(){var a=document.getElementsByTagName("pre"),d=document.getElementsByTagName("code"),c,e=[];for(c=d.length>>>0;c--;)e[c]=d[c];for(c=0;c<a.length;++c)a[c].getElementsByTagName("code").length||e.push(a[c]);o(e,0)}}}();
window.addEventListener?window.addEventListener("load",Rainbow.a,!1):window.attachEvent("onload",Rainbow.a);Rainbow.onHighlight=Rainbow.d;Rainbow.addClass=Rainbow.c;window.b=window.b||{};
Rainbow.extend([{matches:{1:{name:"keyword.operator",pattern:/\=/g},2:"string"},pattern:/(\(|\s|\[|\=)(('|")[\s\S]*?(\3))/gm},{name:"comment",pattern:/\/\*[\s\S]*?\*\/|(\/\/|\#)[\s\S]*?$/gm},{name:"integer",pattern:/\b(0x[\da-f]+|\d+)\b/g},{name:"constant",pattern:/\b[A-Z0-9_]{2,}\b/g},{matches:{1:"keyword"},pattern:/\b(and|array|as|bool(ean)?|c(atch|har|lass|onst)|d(ef|elete|ie|o(uble)?)|e(cho|lse(if)?|xit|xtends)|f(inally|loat|or(each)?|unction)|global|if|import|int(eger)?|long|new|object|or|pr(int|ivate|otected)|public|return|self|st(ring|ruct|atic)|switch|th(en|is|row)|try|(un)?signed|var|void|while)(?=\(|\b)/g},{name:"constant.language",
pattern:/true|false|null/g},{name:"keyword.operator",pattern:/\+|\!|\-|&(gt|lt|amp);|\||\*|\=/g},{matches:{1:"function.call"},pattern:/(\w+?)(?=\()/g},{matches:{1:"keyword",2:"meta.function-call"},pattern:/(function)\s(.*?)(?=\()/g}]);
